// <auto-generated />
namespace Reverb.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddConnections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddConnections));
        
        string IMigrationMetadata.Id
        {
            get { return "201710131904501_AddConnections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
